name: Multiple Python Versions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8,3.9,3.11]
    steps:
      - uses: actions/checkout@v3
      - name: set up Python ${{ matrix.python-version }} 
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }} 
      - name: install packages
        run: make install
      - name: test
        run: make test
      - name: lint
        run: make lint
      - name: format
        run: make format
