name: Test

on:
  workflow_run:
    workflows: ["Install"]
    branches: ["main"]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install packages
      run: pip install -r requirements.txt
    - run: make test
